version: "3.9"

services:
  tic-tac-toe:
    build: .
    image: tictac_img
    container_name: tictac_con
    ports:
      - "8080:80"   # access app on http://localhost:8080
    restart: unless-stopped
